/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vptree_VPEntry */

#ifndef _Included_vptree_VPEntry
#define _Included_vptree_VPEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vptree_VPEntry
 * Method:    arrpush
 * Signature: ([Ljava/lang/Object;Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_vptree_VPEntry_arrpush
  (JNIEnv *, jobject, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
