#!/usr/bin/env bash

clang -lm -lpthread -Ofast -march=native -g -fsanitize=address vpt_test.c
./a.out
echo 'vpt_test completed.'

clang -lm -lpthread -Ofast -march=native -g -fsanitize=address vpt_reclaim_test.c
./a.out
echo 'vpt_reclaim_test completed.'

# Remove -fsanitize=address because of bug/feature limitation in asan. It cannot track the lifetime of more than a few million threads.
clang -lm -lpthread -Ofast -march=native -g vpt_sizes_test.c
./a.out
echo 'vpt_sizes_test completed.'

rm a.out
